---
- name: Ensure OpenSSL is installed
  package:
    name: openssl
    state: present

- name: Output directory for Diffie-Hellman parameters exists
  file:
    path: "{{ dhparam_file | dirname }}"
    state: directory

- name: The Diffie-Hellman parameter file is generated
  command: "openssl dhparam -out '{{ dhparam_file }}' {{ dhparam_size }}"
  args:
    creates: "{{ dhparam_file }}"

- name: Check if crontab exists
  stat:
    path: /etc/crontab
  register: crontab

- include: cron.yml
  when: crontab.stat.exists == True
